Revert rounding of gain in Edfa.to_json
This reverts a change introduced in commit e1f2c55, rounding the gain
in the Edfa.to_json method to 6 digits. The use of round in the the
to_json output has at least two problems:

1. It causes saving of the network json before auto-design to crash
when the gain is None. For example, running:

gnpy-transmission-example meshTopologyExampleV2.json
--save-network-before-autodesign test.json

crashes with:

TypeError: type NoneType doesn't define __round__ method

2. If the user inputs a network topology file where the gain is
specified with more than 6 digits, the output file will be different
from the input causing potential confusion.

Signed-off-by: Jonas Mårtensson <jonas.martensson@ri.se>
Change-Id: Id97c3f426a760830cab17c0e98e63e711a934796