fix: yang-to-legacy does not convert api items
solve the issue reported by renato:
legacy_data = yang_to_legacy(json.loads(request.json))

and then I expect to be able to read:

service = legacy_data['gnpy-path-computation:services']
topology = legacy_data['gnpy-network-topology:topology']
equipment = legacy_data['gnpy-eqpt-config:equipment']

but I get this error:

cr = raman_coefficient.pop('cr')
TypeError: 'str' object cannot be interpreted as an integer

----

because there was no real conversion to legacy of each item
in the formatted request

Signed-off-by: EstherLerouzic <esther.lerouzic@orange.com>
Change-Id: I7cd51a657d9645233acf86babf8df42eee66e41d