Revert rounding of Edfa gain and Fiber loss in to_json methods
This reverts changes introduced in commit e1f2c55, rounding the gain in
the Edfa.to_json method and the loss in the Fiber.to_json methods to 6
digits. The use of round in the to_json output has several problems:

1. It causes saving of the network json before auto-design to crash
when the gain is None. For example, running:

gnpy-transmission-example meshTopologyExampleV2.json
--save-network-before-autodesign test.json

crashes with:

TypeError: type NoneType doesn't define __round__ method

2. It also causes saving of the network json to crash when wavelength
dependent loss_coef is specified as a dict.

3. If the user inputs a network topology file where the gain is
specified with more than 6 digits, the output file will be different
from the input causing potential confusion.

This patch instead solves the problem that commit e1f2c55 addressed,
i.e. that loss_coef * 1e-3 * 1e3 (converting from km to m and back)
results in 0.21000000000000002 when input loss_coef is 0.21, by storing
the original "per km" loss_coef in a seperate attribute and referencing
this in Fiber.to_json.

Signed-off-by: Jonas Mårtensson <jonas.martensson@ri.se>
Change-Id: Id97c3f426a760830cab17c0e98e63e711a934796